name: pub_api_client
description: An API Client for Pub to interact with public package information.
version: 2.2.1
homepage: https://github.com/leoafarias/pub_api_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  oauth2: ^2.0.1
  path: ^1.8.2
  pubspec: ^2.3.0

dev_dependencies:
  build_runner: ^2.3.2
  build_version: ^2.1.1
  freezed: ^2.3.0
  json_serializable: ^6.5.4
  pedantic: ^1.11.1
  test: ^1.22.0
  test_cov: ^1.0.1
